/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/dispatch': typeof DispatchRoute
  '/privacy': typeof PrivacyRoute
  '/tasks/$id': typeof TasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/dispatch': typeof DispatchRoute
  '/privacy': typeof PrivacyRoute
  '/tasks/$id': typeof TasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/dispatch': typeof DispatchRoute
  '/privacy': typeof PrivacyRoute
  '/tasks/$id': typeof TasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connectors' | '/dispatch' | '/privacy' | '/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connectors' | '/dispatch' | '/privacy' | '/tasks/$id'
  id: '__root__' | '/' | '/connectors' | '/dispatch' | '/privacy' | '/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DispatchRoute: typeof DispatchRoute
  PrivacyRoute: typeof PrivacyRoute
  TasksIdRoute: typeof TasksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRoute,
  DispatchRoute: DispatchRoute,
  PrivacyRoute: PrivacyRoute,
  TasksIdRoute: TasksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
